apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: h3oj90yeg-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-87d7d8a936.46c4.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:ef6d1a64efce142ebdaf234237589d5567abdf1d@sha256:ce082fcf0bad76ae4140d158dba7a98a91e360325fcff452512062e778dd96f1
        name: container-image  
